config/routes.rb
Autodor::Application.routes.draw do
  get 'point/:object_type' => 'points#query'
  resources :points

  get "home/links"

  match ':controller(/:action)'
  match 'moar' => 'home#moar'
  match 'news' => 'page#news'
  match 'points' => 'points'
  match 'map' => 'home#regional_map'
  match 'laws' => 'page#laws'

  root :to => "home#index"

end

app/models/news.rb
class News
  require 'open-uri'
  require 'iconv'
  
  def self.load
	Iconv.iconv('UTF-8', 'WINDOWS-1251', open('http://www.ukravtodor.gov.ua/clients/ukrautodor.nsf/news_value.js').readlines().join('')).join('')
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  def self.by_object_type(object_type)
    where(:object_type => object_type)
  end
  
  def self.by_object_type_in_bbox(object_type, lat1, lon1, lat2, lon2, extent)
    lat_min = [lat1, lat2].min
    lon_min = [lon1, lon2].min
    lat_max = [lat1, lat2].max
    lon_max = [lon1, lon2].max
    if extent > 0 then
      lat_min -= 0.2
      lat_max += 0.2
      lon_min -= 0.1
      lon_max += 0.1
    end
    where(:object_type => object_type, :lat => (lat_min .. lat_max), :lon => (lon_min .. lon_max))
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	attr_accessor :points
	
	def initialize
		self.points = []
	end
	
	def index
		render :layout => 'admin'
	end
	
	def savePoint
		redirect_to :action => :index
	end

	def removePoint
		redirect_to :action => :index
	end
	
	def uploadImg
		p = Point.save(params[:upload])
		
		redirect_to :action => :index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_locale
  
  def extract_locale_from_tld
    res = request.host.split(',').last

    res if res != request.host
  end
  
  def extract_locale_from_subdomain
    res = request.subdomains.first 
    
    res if !request.subdomains.empty? and res != request.host
  end
  
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end
  
  def set_locale
    extracted_locale = params[:locale] ||
                       session[:locale] ||
                       #extract_locale_from_subdomain ||
                       #extract_locale_from_tld ||
                       extract_locale_from_accept_language_header

    #logger.debug "Locales: #{ [ params[:locale], session[:locale], extract_locale_from_subdomain, extract_locale_from_tld, extract_locale_from_accept_language_header ].each { |l| l.inspect } }"
    logger.debug "Default locale: #{ extracted_locale }"

    I18n.locale = (I18n::available_locales.include? extracted_locale.to_sym) ? extracted_locale :
        I18n.default_locale

    session[:locale] = I18n.locale if params[:locale]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'regional'
	
	before_filter :page_setup, :except => [ :weather ]
	
	def index
	end

	def moar
		render 'moar', :layout => 'moar'
	end
	
	def map
		render 'home/map', :layout => 'map'
  end
  
  def regional_map
		render 'home/regional_map', :layout => 'regional_map'
  end
	
	def weather
		url = "http://62.244.10.66/gmaps/connector.php?lang=en&type=large&"
		url += "x1=#{params[:x1]}&x2=#{params[:x2]}&y1=#{params[:y1]}&y2=#{params[:y2]}&zoom=#{params[:zoom]}"

		body = CurbFu.get(url).body
		response = JSON.parse(body)
		
		cnt = 0
		points = ""
		
		response.each do |i|
			points += %{
<Style id="moo#{ cnt }">
	<IconStyle>
		<Icon>
			<href>http://www.meteoprog.ua/pictures/markers/#{ i['link'] }</href>
		</Icon>
		<scale>3</scale>
	</IconStyle>
</Style>

<Placemark>
	<styleUrl>#moo#{ cnt }</styleUrl>
	<Point>
		<coordinates>#{ i['y'] },#{ i['x'] }</coordinates>
	</Point>
</Placemark>
				}
				
			cnt += 1
		end
			
		kml = %{<?xml version="1.0" encoding="UTF-8"?>

<kml xmlns="http://www.opengis.net/kml/2.2">
	#{ points }
</kml>
			}
			
		render :xml => kml
	end

	private

	def page_setup
		@languages = [ "ru", "ua", "en" ]
		@current_lang = "ua"
		@news = News.load
	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  layout 'regional'

  def contact
  end

  def support
  end

  def about
  end

	def notify
	end
  
  def laws
  end

	def news
    render 'news', :layout => 'news'
  end
  
  def send_notify
  	ReportMailer.new_report(params[:message]).deliver
	session[:return_to] ||= request.referer
	redirect_to session[:return_to]
  end

	def links
    @links = [
				MLink.new('links.euro2012highway', 'http://euro2012highway.blogspot.com/', 'euro2012highway_thumb.png'),
				MLink.new('links.diprodor', 'http://diprodor.com', 'diprodor_thumb.png'),
				MLink.new('links.ukrautodor', 'http://ukravtodor.gov.ua/clients/ukrautodor.nsf', '0.jpg'),
				MLink.new('links.uefa_com', 'http://www.uefa.com/uefaeuro2012/', '1.jpg'),
				MLink.new('links.euro_2012', 'http://euro-2012.com.ua/', '2.jpg'),
				MLink.new('links._2012ua', 'http://2012ua.net/', '3.jpg'),
		]
  end
end

class MLink
	attr_accessor :title, :url, :img

	def initialize(a, b, c)
	  self.title = a
	  self.url = b
	  self.img = c
	end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  layout "points"

  def query
    object_type = params[:object_type]

	if (object_type == 'monument')
		send_kml("monuments_uk.kml") 
		return
	end

    lat1 = params[:lat1]
    lat2 = params[:lat2]
    lon1 = params[:lon1]
    lon2 = params[:lon2]
    extent = params[:extend]

	if not object_type then
      @points = []
    elsif lat1 && lon1 && lat2 && lon2 then
      @points = Point.by_object_type_in_bbox object_type, lat1.to_f, lon1.to_f, lat2.to_f, lon2.to_f, extent.to_f
    else
      @points = Point.by_object_type object_type
    end
  end

  def send_kml(filename)
	full_file_name = "#{Rails.root}/db/data/#{filename}"
	send_data File.open(full_file_name).read, :type => :kml
  end

  def index
    @points = Point.all
  end

  def show
    @point = Point.find(params[:id])
  end

  def new
    @point = Point.new
  end

  def edit
    @point = Point.find(params[:id])
  end

  def create
    @point = Point.new(params[:point])
    
    if (!params[:image].nil?)
			io = params[:image]
			path = File.join('public/images/upload', io.original_filename)

			File.open(path, 'wb') do |f|
				f.write(io.read)
			end

			@point.image = File.join('upload', io.original_filename)
    end

		if @point.save
			#updateIncidentsKML()
			redirect_to(@point, :notice => 'Point was successfully created.')
		else
			render :action => "new"
		end
  end

  def update
    @point = Point.find(params[:id])
    
    if (!params[:image].nil?)
			io = params[:image]
			path = File.join('public/images/upload', io.original_filename)

			File.open(path, 'wb') do |f|
				f.write(io.read)
			end

			@point.image = File.join('upload', io.original_filename)
    end
    
    if @point.update_attributes(params[:point])
	  #updateIncidentsKML()
      redirect_to(@point, :notice => 'Point was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @point = Point.find(params[:id])
    @point.destroy
    
    redirect_to(points_url)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/object_helper.rb
module ObjectHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/points_helper.rb
module PointsHelper
  def object_types
    [ 'custom', 'police', 'carService', 'gas', 'hotel', 
      'monument', 'roadCondition', 'recreationArea', 'food', 'medicine' ]
  end
  
  def object_type_names
    names = {}
    object_types.each { |type| names[type] = t("objects.#{type}") }
    names
  end
end

app/views/admin/index.html.haml
:javascript
	$(function() {
		initMarkerList();
		
		$("input:checkbox").click(function() {
			$(this).children().toggleClass('checked');
			$(this).toggleClass('checked');
		});

		updateSearchInputs();

		$("#searchQuery").keydown(function(evt) {
			if (evt.keyCode == 13) {
				$("#searchControl").click();
			}
		});
		
		$(".markerItem input.searchQuery").attr("title", $(".translations #markerItem").html());
		$(".markerItem a").attr("title", $(".translations #markerRemove").html());
		$("#searchQuery").attr("title", $(".translations #searchQuery").html());
		$("#clearRoute").attr("title", $(".translations #clearRoute").html());
		$(".lang").attr("title", $(".translations #langChanger").html());
		$(".help img").attr("title", $(".translations #helpIcon").html());
		$("#printRoute img").attr("title", $(".translations #printIcon").html());
		
		$("[title]").mbTooltip({ // also $([domElement]).mbTooltip  >>  in this case only children element are involved
			opacity: .97,       //opacity
			wait: 200,           //before show
			cssClass: "default",  // default = default
			timePerWord: 70,      //time to show in milliseconds per word
			hasArrow: false,			// if you whant a little arrow on the corner
			hasShadow: true,
			imgPath: "public/images/tooltip/",
			ancor: "mouse", //"parent"  you can ancor the tooltip to the mouse position or at the bottom of the element
			shadowColor: "black", //the color of the shadow
			mb_fade: 200 //the time to fade-in
		});
	});

.logo
	%a{ :href => "/", :title => "Euro 2012 Ukraine-Poland" }
		= image_tag "euro2012-logo.png", { :alt => "Euro 2012 Ukraine-Poland" }

.help{ :style => "display: none;" }
	= image_tag "question_small.png"

.menu
	%ul
		%li.objects
			%ul
				%li
					= image_tag '/images/objects/moar/gas.png', { :id => "gas", :title => "#{t('objects.gas')}", :onClick => "switchLayer('gas'); $(this).toggleClass('checked');" }

				%li
					= image_tag '/images/objects/moar/service.png', { :id => "carService", :onClick => "switchLayer('carService'); $(this).toggleClass('checked');", :title => "#{t('objects.carService')}" }

				%li
					= image_tag '/images/objects/moar/hotel.png', { :id => "hotel", :onClick => "switchLayer('hotel'); $(this).toggleClass('checked');", :title => "#{t('objects.hotel')}" }

				%li
					= image_tag '/images/objects/moar/historical.png', { :id => "monument", :onClick => "switchLayer('monument'); $(this).toggleClass('checked');", :title => "#{t('objects.monument')}" }

				%li
					= image_tag '/images/objects/moar/incidents.png', { :id => "roadCondition", :onClick => "switchLayer('roadCondition'); $(this).toggleClass('checked');", :title => "#{t('objects.roadCondition')}" }

				%li
					= image_tag '/images/objects/moar/weather.png', { :id => "weather", :onClick => "switchLayer('weather'); $(this).toggleClass('checked');", :title => "#{t('objects.weather')}" }

				%li
					= image_tag '/images/objects/moar/webcam.png', { :id => "webCams", :onclick => "switchLayer('webCams'); $(this).toggleClass('checked');", :title => "#{t('objects.webCam')}" }

		%li.search
			%input#searchQuery{ :type => "edit", :name => "query", :size => "30" }
			%input#searchControl{ :type => "button", :value => "#{t('panel.search')}", :onClick => "geoSearch();" }

		%li.lang
			= image_tag "flags/#{ I18n.locale }.png", { :style => "margin-right: 5px;", :curr_lang => I18n.locale }

			%ul
				-I18n::available_locales.each do |l|
					-if I18n.locale != l
						%li
							%a{ :href => "?locale=#{ l }" }
								=image_tag "flags/#{ l }.png"

.content
	.panel
		%form{ :action => 'savePoint', :method => 'post' }
			%select{ :size => '1', :name => 'type', :value => 'POI type' }
				%option
					moo
				%option
					foo
				%option
					ololo
				%option
					zaooza~!
			
			= text_field_tag :name
			= text_area_tag( :description, "", :size => "20x6" )
			
			%form{ :action => 'uploadImg', :multipart => 'true' }
				= file_field( :upload, :datafile )
				= submit_tag 'Add'
		
			%br/
			
			= submit_tag 'Save'
		%br/
			
		.searchResults#routingPanel

	.map
		#map

	.translations{ :style => "display: none;" }
		#add_point
			= t "panel.add_point"

		#add_start_point
			= t "panel.add_start_point"

		#add_end_point
			= t "panel.add_end_point"

		#title_unknown
			= t "place.unknown"
			
		#markerItem
			= (t "controls.markerItem").html_safe
			
		#markerRemove
			= (t "controls.markerRemove").html_safe
		
		#searchQuery
			= (t "controls.searchQuery").html_safe
		
		#clearRoute
			= (t "controls.clearRoute").html_safe
		
		#langChanger
			= (t "controls.langChanger").html_safe
			
		#helpIcon
			= (t "controls.help").html_safe
			
		#printIcon
			= (t "controls.print").html_safe

app/views/home/_panel.html.haml
:javascript
	$(function() {
		$("#tabs").tabs();
		$("#addWaypoint, #weatherControl").button();
		$(".routeType").buttonset();
	});

#tabs
	%ul
		%li
			%a{ :href => "#tabsRouting" }
				= t('panel.routes')
				
		%li
			%a{ :href => "#tabsSearch" }
				= t('panel.search')
				
		%li
			%a{ :href => "#tabsObjects" }
				= t('panel.objects')

	= render :partial => 'home/tabRoute'

	= render :partial => 'home/tabSearch'

	= render :partial => 'home/tabObjects'

%br/

app/views/home/_panelQuickLinks.html.haml
#panelQuickLinks{ :class => "ui-widget-content ui-corner-all" }
	#quickHeading{ :class => "ui-widget-header ui-corner-all" } 
		%h3
			= t('panel.quickLinks')
		
	%table{ :style => "width: 100%; text-align: center;" }
		%tr
			%td.momoClass
				%a{ :class => "link", :onClick => "mapToPoint('Kyiv stadium', 15)", :title => "#{ (t "links.goto") % (t "place.kyiv") }" }
					= image_tag '/images/kiev_small.png'
					
					%br/
					
					= t('place.kyiv')
					
			%td.momoClass
				%a{ :class => "link", :onClick => "mapToPoint('Kharkiv stadium', 15)", :title => "#{ (t "links.goto") % (t "place.kharkiv") }" }
					= image_tag '/images/kharkiv_small.png'
					
					%br/
					
					= t('place.kharkiv')
					
		%tr
			%td.momoClass
				%a{ :class => "link", :onClick => "mapToPoint('Donetsk stadium', 15)", :title => "#{ (t "links.goto") % (t "place.donetsk") }" }
					= image_tag '/images/donetsk_small.png'
					
					%br/
					
					= t('place.donetsk')
					
			%td.momoClass
				%a{ :class => "link", :onClick => "mapToPoint('Lviv stadium', 15)", :title => "#{ (t "links.goto") % (t "place.lviv") }" }
					= image_tag '/images/lviv_small.png'
					
					%br/
					
					= t('place.lviv')

app/views/home/_tabObjects.html.haml
#tabsObjects
	:javascript
		$(function() {
			$(".objectControls").buttonset();
		});
		
	.objectControls{ :style => "text-align: center;" }

		%input#weather{ :type => "checkbox", :onClick => "switchLayer('weather');" }
			%label{ :for => "weather", :title => "#{t('objects.weather')}" }
				= image_tag '/images/controls/weather.png'

		%input#webCam{ :type => "checkbox", :onClick => "switchLayer('webCams');" }
			%label{ :for => "webCam", :title => "#{t('objects.webCam')}" }
				= image_tag '/images/objects/camera.png'

		%input#monument{ :type => "checkbox", :onClick => "switchLayer('monument');" }
			%label{ :for => "monument", :title => "#{t('objects.monument')}" }
				= image_tag '/images/objects/monument.gif'

		%input#roadCondition{ :type => "checkbox", :onClick => "switchLayer('roadCondition');" }
			%label{ :for => "roadCondition", :title => "#{t('objects.roadCondition')}" }
				= image_tag '/images/objects/incidents.png'
				
	
	%br/
		
	.objectControls{ :style => "text-align: center;" }
		%input#gas{ :type => "checkbox", :onClick => "switchLayer('gas');" }
			%label{ :for => "gas", :title => "#{t('objects.gas')}" }
				= image_tag '/images/objects/gas.gif'
				
		%input#carService{ :type => "checkbox", :onClick => "switchLayer('carService');" }
			%label{ :for => "carService", :title => "#{t('objects.carService')}" }
				= image_tag '/images/objects/car_service.gif'
						
		%input#hotel{ :type => "checkbox", :onClick => "switchLayer('hotel');" }
			%label{ :for => "hotel", :title => "#{t('objects.hotel')}" }
				= image_tag '/images/objects/hotel.gif'
				
		%input#food{ :type => "checkbox", :onClick => "switchLayer('food');" }
			%label{ :for => "food", :title => "#{t('objects.food')}" }
				= image_tag '/images/objects/food.png'
	
	%br/

	.objectControls{ :style => "text-align: center;" }

		%input#recreationArea{ :type => "checkbox", :onClick => "switchLayer('recreationArea');" }
			%label{ :for => "recreationArea", :title => "#{t('objects.recreationArea')}" }
				= image_tag '/images/objects/recreationArea.png'
			
		
		%input#medicine{ :type => "checkbox", :onClick => "switchLayer('medicine');" }
			%label{ :for => "medicine", :title => "#{t('objects.medicine')}" }
				= image_tag '/images/objects/medicine.gif'
		
		%input#police{ :type => "checkbox", :onClick => "switchLayer('police');"}
			%label{ :for => "police", :title => "#{t('objects.police')}" }
				= image_tag '/images/objects/police.png'


		%input#custom{ :type => "checkbox", :onClick => "switchLayer('custom');"}
			%label{ :for => "custom", :title => "#{t('objects.custom')}" }
				= image_tag '/images/objects/custom.png'

app/views/home/_tabRoute.html.haml
- @locale = I18n::locale
:javascript
	$(function() {
		$("#clearRoute, #printRoute").button().hide();
		$(".routeType").buttonset();
		$("#addWaypoint").button();
		
		$(":radio[checked], :checkbox[checked]").removeAttr("checked");
		$("#car").attr("checked", "checked");
		
		$.datepicker.setDefaults( $.datepicker.regional[ "" ] );
		$( "#leaveDate" ).datepicker( $.datepicker.regional[ "#{@locale}" ] );
	});

#tabsRouting
	%label{ :for => "leaveDate" }= t('panel.leaveDate')
	%br/
	%input#leaveDate{ :type => "text" }
	
	.markerList

	%br/
	
	.routeControls
		%input#addWaypoint{ :type => "checkbox", :onClick => "return false;" }
			%label{ :for => "addWaypoint", :style => "width: 90%", :title => "#{ t "panel.add_point" }" }
				= image_tag "controls/add_waypoint.png"

		%br/
		%br/

		.routeType
			%input#car{ :type => "radio", :name => "routeType", :onClick => "changeRouteType('car/shortest');" }
				%label{ :for => "car", :title => "#{ t "panel.car_fastest_route" }" }
					= image_tag "controls/car.png"

			%input#truck{ :type => "radio", :name => "routeType", :onClick => "changeRouteType('car');" }
				%label{ :for => "truck", :title => "#{ t "panel.car_shortest_route" }" }
					= image_tag "controls/truck.png"
			
		%br/
			
		%a#printRoute{ :name => "printRoute", :onClick => "printRoute();", :title => "#{ t "panel.print_route" }" }
			= image_tag "controls/print_icon.png"
			
		%a#clearRoute{ :name => "clearRoute", :style => "cursor: pointer;", :onClick => "clearRoute();", :title => "#{ t "panel.clear_route" }" }
			= image_tag "controls/clear.png"
			
		%br/
	%br/
		
	#routingPanel
		%br/

app/views/home/_tabSearch.html.haml
#tabsSearch
	:javascript
		$(function() {
			$("#searchControl").button();
		});
		
	.searchControls
		%input#searchQuery{ :type => "edit", :name => "query", :title => "#{ t "panel.search_query" }" }
		
		%br/
		%br/
		
		%input#searchControl{ :type => "submit", :value => "#{t 'panel.doSearch'}", :title => "#{t 'panel.doSearchTip'}", :onClick => "geoSearch();" }
	
	%br/
		
	.searchResults

app/views/home/index.html.haml
%h1 Функциональное назначение.
Интернет-сайт реализует социальные обязательства государства по обеспечению водителей информацией:
%ul
	%li О существующей сети автомобильных дорог государственного значения и параллельные маршруты с дорог местного значения;
	%li О реальном состоянии проезда по дороге, наличие "критических ситуаций" (гололеда, значительной неровности покрытия, ямковитых участков, мест ДТП с тяжелыми последствиями, мест природных и техногенных катастроф, участков на которых проводятся ремонтные работы и т.п.);
	%li О местоположении пунктов медицинской помощи, площадок отдыха, пунктов сервиса (АЗС, СТО и др.);
	%li Другой информации, которая может повысить безопасность движения по дорогам.

= image_tag 'e-roads-ukraine.jpg'

app/views/home/map.html.haml
%table.main
	%tr
		%td.map
			#map

		%td.copyright{ :width => "370" }
			= render :partial => 'home/panel'

app/views/home/regional_map.html.haml
.col1
	#map
#panel.col2
	= render :partial => 'home/panel'

app/views/layouts/admin.html.haml
<!DOCTYPE html>
%html
	%head
		%title Autodor
	
		= stylesheet_link_tag 'moar'
		= stylesheet_link_tag 'map'
		= stylesheet_link_tag 'sunny/sunny'
		= stylesheet_link_tag 'contextmenu/jquery-contextmenu'
		= stylesheet_link_tag 'mbTooltip'
		
		= javascript_include_tag 'jquery'
		= javascript_include_tag 'jquery-ui'
		= javascript_include_tag 'rails'
		= javascript_include_tag 'http://tile.cloudmade.com/wml/latest/web-maps-lite.js'
		= javascript_include_tag 'http://api.webcams.travel/jsapi?devid=0be425afeaead9f0893c0bae527be9a0'
		= javascript_include_tag 'jquery-contextmenu'
		= javascript_include_tag 'jquery.timers'
		= javascript_include_tag 'jquery.dropshadow'
		= javascript_include_tag 'mbTooltip'
		= javascript_include_tag 'cities'
		= javascript_include_tag 'application_moar'
		= javascript_include_tag 'patchy'
		= javascript_include_tag 'http://gostats.com/js/counter.js'
		
		:javascript
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-22303667-2']);
			_gaq.push(['_trackPageview']);

			(function() {
			  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		
		:javascript
			_gos='gostats.com';_goa=745684;
			_got=5;_goi=1;_gol='visitor statistics';_GoStatsRun();
		
		= csrf_meta_tag
	
	%body
	
		= yield

		%a{ :target => "_blank", :title => "visitor statistics", :href => "http://gostats.com" }
			= image_tag "http://gostats.com/bin/count/a_745684/t_5/i_1/counter.png", :alt => "visitor statistics", :style => "border-width:0"

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title Autodor
		= stylesheet_link_tag 'main'
		= stylesheet_link_tag 'map'
		= stylesheet_link_tag 'sunny/sunny'
		= stylesheet_link_tag 'contextmenu/jquery-contextmenu'
		= javascript_include_tag 'jquery'
		= javascript_include_tag 'jquery-ui'
		= javascript_include_tag 'rails'
		= javascript_include_tag 'http://tile.cloudmade.com/wml/latest/web-maps-lite.js'
		= javascript_include_tag 'http://api.webcams.travel/jsapi?devid=0be425afeaead9f0893c0bae527be9a0'
		= javascript_include_tag 'jquery-contextmenu'
		= javascript_include_tag 'google-analytics'
		= csrf_meta_tag
	%body
		.header
			.logo
				%a{ :href => "/", :title => "Euro 2012 Ukraine-Poland" }
					=image_tag "euro2012-logo.jpg", :alt => "Euro 2012 Ukraine-Poland"

			.language_icons
				%a{ :href => "?locale=en" }
					=image_tag "flags/en.png"
				%a{ :href => "?locale=uk" }
					=image_tag "flags/uk.png"
				%a{ :href => "?locale=ru" }
					=image_tag "flags/ru.png"					
			
			.menu
				%a{ :href => "/" }= t('menu.map')
				%a{ :href => "/page/support" }= t('menu.support')
				%a{ :href => "/page/links" }= t('menu.links')
				%a{ :href => "/page/about" }= t('menu.about')

		.main
			= yield

app/views/page/about.html.haml
.moo{ :style => "text-align: center;" }
	%h1{ :style => "float: left;" }
		= (t 'about.about').html_safe

	%br/

	= image_tag "/images/datacenter.jpg"

	%br/

	%p
		= (t 'about.description').html_safe

app/views/page/news.html.haml
= stylesheet_link_tag 'news'

%h1
	= t 'pages.news'

%br/

- @news.each do |e|
	.newsItem
		= e.to_html.html_safe

app/views/points/edit.html.haml
:javascript
	$(function() {
		// var pos = new CM.LatLng(#{@point.lat}, #{@point.lon});
		var updateMarker = function() {
			if (!currMarker)
				return;

			var pos = currMarker.getLatLng();
			$('#point_lat').val(pos.lat());
			$('#point_lon').val(pos.lng());
		};

		//marker = new CM.Marker(pos, { title: '#{@point.name}', icon: '#{@point.image}', draggable: true, draggedEvent: updateMarker });
		//marker.bindInfoWindow('<h3>#{@point.name}</h3>');
		//map.addOverlay(marker);
		
		if (!currMarker)
			currMarker = createMarker(#{@point.lat}, #{@point.lon}, {'addOverlay': true, 'draggable': true, 'moveEvent': updateMarker});
	});


%strong= t('admin.editingPoint')

= render 'form'
= link_to t('admin.show'), @point
|
= link_to t('admin.back'), points_path

app/views/points/index.html.haml
= link_to t('admin.newPoint'), new_point_path 

%br/

- @points.each do |point|
	= link_to t('admin.show'), point 
	= link_to t('admin.edit'), edit_point_path(point) 
	= link_to t('admin.delete'), point, :confirm => t('admin.areYouSure'), :method => "delete"
	= point.name 
	%br/

app/views/points/new.html.haml
%strong= t('admin.newPoint')

= render 'form'
= link_to t('admin.back'), points_path

app/views/points/show.html.haml
:javascript
	$(function() {
		var marker = createMarker(#{@point.lat}, #{@point.lon}, {'addOverlay': true, 'draggable': false});
	});

%p{ :id => "notice" }
	= notice

- if @point.object_type
	%p
		%strong
			= t('admin.objectType')
		= object_type_names[@point.object_type]

%p
	%strong
		= t('admin.name')
	= @point.name.html_safe


%p
	%strong
		= t('admin.description')
	= @point.description.html_safe

%p
	%strong
		= t('admin.lat')
	= @point.lat

%p
	%strong
		= t('admin.lon')
	= @point.lon 

- if not @point.image.blank?
	%p
		%strong
			= t('admin.image')
		= image_tag @point.image

= link_to t('admin.edit'), edit_point_path(@point)
|
= link_to t('admin.back'), points_path 